In [7]:
!pip install numPy

Defaulting to user installation because normal site-packages is not writeable


In [24]:
import numpy as np


In [13]:
data = [1,2,3,4,5]
np_array = np.array(data)
print(np_array)

[1 2 3 4 5]


In [14]:
print(np_array + 8)
print(np_array - 8)
print(np_array * 8)
print(np_array / 8)

[ 9 10 11 12 13]
[-7 -6 -5 -4 -3]
[ 8 16 24 32 40]
[0.125 0.25  0.375 0.5   0.625]


In [15]:
data = [[1,2,3],
       [4,5,6],
       [7,8,9]]

np_array = np.array(data)
print(np_array)
print(np_array.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [19]:
data = [[[1,1,1],[2,2,2],[3,3,3]],
        [[4,4,4],[5,5,5],[6,6,6]],
       [[7,7,7],[8,8,8],[9,9,9]]]

np_array = np.array(data)
print(np_array.shape)

(3, 3, 3)


In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
#Reshape
# 6 = 1 *6
# 6 = 2 *3

data = [[2,3,4],
       [3,4,5]]

np_array = np.array(data)
print(np_array.shape)


print(np_array.reshape(1,6))
print(np_array.reshape(3,2))
print(np_array.reshape(6,1))

(2, 3)
[[2 3 4 3 4 5]]
[[2 3]
 [4 3]
 [4 5]]
[[2]
 [3]
 [4]
 [3]
 [4]
 [5]]


In [33]:
np_array.flatten()

array([2, 3, 4, 3, 4, 5])

In [34]:
print(np_array.flatten())

[2 3 4 3 4 5]


In [35]:
np.array([1,2,3]) + np.array([3,4,5])

array([4, 6, 8])

In [36]:
a = np.array([1,2,3])
b = np.array([1,1,1])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 1 1 1]
[[1 2 3]
 [1 1 1]]
